In [1]:
import gym
# import gym_minigrid
# import gym_gridworlds
# from gym_minigrid.wrappers import *
import numpy as np
# import Gridworld

from custom_envs.gridworlds import WindyGridworldEnv, WindyGridworldEnvNoEncode


In [2]:
# env1 = gym.make("WindyGridworld-v0")
# env2 = gym.make("CartPole-v1")
# env3 = gym.make("MiniGrid-Empty-5x5-v0")
# env4 = WindyGridworldEnv()


env = WindyGridworldEnvNoEncode()
env2 = WindyGridworldEnv()
print(env2.observation_space)
print(len(env.observation_space.spaces))
# env3 = FlatObsWrapper(env3)
# print(env4.observation_space)
# print(env4.action_space.n)

# print(sum([i.n for i in env1.observation_space]))

Discrete(70)
2


In [3]:
env = env

env.reset() 
done = False
rr = 0
i = 0
while not done:
    s, r, done, next_s = env.step(0)
    print(s)
    rr += r
    i += 1
    if i == 10:
        done = True
print(rr, i)
# env1.render()



[2 0]
[1 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
[0 0]
-10 10


In [31]:
def _one_hot(sample):
    index = sample[0]*10 + sample[1]
    features = np.zeros(70)
    features[index]=1

    return features


In [33]:
x = (4,4)
_one_hot(x)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [15]:
env = gym.make("CartPole-v1")
environment = "cartpole"


In [16]:
env.reset() 
done = False
rr = 0
i = 0
while not done:
    s, r, done, next_s = env.step(0)
    print(s)
    rr += r
    i += 1
    if i == 10:
        done = True
print(rr, i)
# env1.render()

[ 0.01761609 -0.16308955  0.01155363  0.28634518]
[ 0.0143543  -0.35837435  0.01728054  0.58264952]
[ 0.00718681 -0.55373409  0.02893353  0.8807256 ]
[-0.00388787 -0.74923689  0.04654804  1.18236234]
[-0.01887261 -0.94493098  0.07019529  1.4892657 ]
[-0.03777123 -1.14083405  0.0999806   1.80301711]
[-0.06058791 -1.33692082  0.13604094  2.12502375]
[-0.08732632 -1.53310828  0.17854142  2.45645878]
[-0.11798849 -1.72923858  0.22767059  2.79819037]
9.0 9
